New script for tracing DToL status in Ensembl
Ensembl/ensembl-genes pull request #37
Opened 2022-05-09 13:40 UTC by leannehaggerty

We needed something to quickly give us a list of databases that need to be added to the DToL projects page... so here it is.

It accesses the gb_assembly_registry and ensembl_metadata_qrp databases for info

The script will return:
- a summary of the DToL assemblies in Ensembl <-summary 1>
- a list of the GCAs that are in progress <-in_progress 1> (currently returns 0, none are set to "in progress" in the genebuild_status table in gb_assembly_registry)
- a list of GCAs that have not been annotated yet <-unannotated 1>
- a list of core dbs for assemblies that have been annotated but do not appear on the projects page yet

There is potential to add checks on rapid release too (e.g. what has been annotated and not released)

2022-05-10 08:35 UTC, williamstark01 commented
@leannehaggerty nothing wrong with your PR, the tests are failing due to another Python script, I'm preparing another PR to resolve this

2022-05-10 11:00 UTC, williamstark01 requested changes
Nice script, just a couple improvements suggestions.

2022-05-11 08:36 UTC, leannehaggerty commented
Changes addressed.

2022-05-11 09:44 UTC, williamstark01 commented
@leannehaggerty I see that you had to do a couple of tries to fix the README rendering, sorry about that. Just code fencing would have done the trick, I pushed a new commit with that.

Markdown has been extensively adopted today and it's both very useful and simple, so it's good to know how it works. (And everybody loves it! :)

Here's a cheat sheet, I think that's all anyone would need:
https://www.markdownguide.org/cheat-sheet/

2022-05-18 11:29 UTC, williamstark01 approved these changes
Looks good, nice job.

2022-05-18 11:30 UTC, merged

2022-05-18 11:31 UTC, williamstark01 commented
@leannehaggerty I'm not deleting the branch in case you want to reuse it for future additions, feel free to delete it if it's not needed anymore.